namespace BackEnd.DTOs;

public record ProfileResponse(
    int Id,
    int UserId,
    string? DisplayName,
    string? Skills,
    string? Interests,
    string? ExperienceLevel,
    string? Education,
    string? PreferredIndustries,
    string? Location,
    string? Bio,
    string? LinkedInUrl,
    string? PortfolioUrl,
    string? Gender,
    string? UgCourse,
    string? UgSpecialization,
    string? UgCgpaOrPercentage,
    bool? HasAdditionalCertifications,
    string? CertificateCourseTitles,
    bool? IsWorking,
    string? FirstJobTitle,
    string? MastersField,
    DateTime? UpdatedAt);

public record ProfileCreateOrUpdateRequest(
    string? Skills,
    string? Interests,
    string? ExperienceLevel,
    string? Education,
    string? PreferredIndustries,
    string? Location,
    string? Bio,
    string? LinkedInUrl,
    string? PortfolioUrl,
    string? DisplayName,
    string? Gender,
    string? UgCourse,
    string? UgSpecialization,
    string? UgCgpaOrPercentage,
    bool? HasAdditionalCertifications,
    string? CertificateCourseTitles,
    bool? IsWorking,
    string? FirstJobTitle,
    string? MastersField);
